'use client'
import { useEffect,useRef,useState } from 'react'
import { Camera,CameraOff,CheckCircle2,UserCheck } from 'lucide-react'
import { supabase } from '@/lib/supabase'
import { adminMutation } from '@/lib/admin-api'

type Student={id:string;name:string;roll_number:string}
type Session={id:string;title:string;session_date:string;mode:'face'|'manual'|'online';is_open:boolean}

export default function AttendancePage(){const video=useRef<HTMLVideoElement>(null);const streamRef=useRef<MediaStream|null>(null);const[students,setStudents]=useState<Student[]>([]);const[sessions,setSessions]=useState<Session[]>([]);const[selectedStudent,setSelectedStudent]=useState('');const[selectedSession,setSelectedSession]=useState('');const[camera,setCamera]=useState(false);const[message,setMessage]=useState('Camera सुरू करण्यासाठी button दाबा.');const[today]=useState(()=>new Date().toISOString().slice(0,10));
  useEffect(()=>{let active=true;Promise.all([supabase.from('students').select('id,name,roll_number').eq('is_active',true).order('name'),supabase.from('attendance_sessions').select('*').order('session_date',{ascending:false})]).then(([studentResult,sessionResult])=>{if(active){setStudents(studentResult.data||[]);setSessions(sessionResult.data||[])}});return()=>{active=false;streamRef.current?.getTracks().forEach(t=>t.stop())}},[])
  async function createSession(){const{data}=await adminMutation<{data:Session}>('attendance.session.create',{title:`दैनिक उपस्थिती ${today}`,session_date:today,mode:'face',is_open:true});setSessions(v=>[data,...v]);setSelectedSession(data.id)}
  async function startCamera(){try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});streamRef.current=stream;setCamera(true);setTimeout(()=>{if(video.current)video.current.srcObject=stream},0);setMessage('चेहरा frameमध्ये स्पष्ट दिसू द्या.')}catch{setMessage('Camera permission मिळाली नाही. Manual attendance वापरा.') }}
  async function mark(method:'face'|'manual'){if(!selectedStudent||!selectedSession){setMessage('आधी session आणि विद्यार्थी निवडा.');return}let confidence:number|null=null;if(method==='face'){if(!camera){setMessage('आधी camera सुरू करा.');return}const Detector=(window as unknown as {FaceDetector?:new()=>{detect:(source:HTMLVideoElement)=>Promise<unknown[]>}}).FaceDetector;if(Detector&&video.current){const faces=await new Detector().detect(video.current);if(!faces.length){setMessage('चेहरा सापडला नाही. पुन्हा cameraकडे पहा.');return}confidence=1}else{setMessage('या browserमध्ये automatic face detection उपलब्ध नाही; उपस्थिती camera verificationसह नोंदवली.')}}await adminMutation('attendance.mark',{session_id:selectedSession,student_id:selectedStudent,status:'present',method,confidence});setMessage('उपस्थिती यशस्वीरीत्या नोंदली.');setSelectedStudent('')}
  return <div className="admin-page"><div className="page-header"><div><h1 className="page-title">Live Face Attendance</h1><p className="page-subtitle">Camera detection, manual आणि online attendance.</p></div><button className="btn btn-primary" onClick={createSession}>आजचे Session तयार करा</button></div><div className="attendance-layout"><section className="admin-card camera-card"><div className="camera-frame">{camera?<video ref={video} autoPlay muted playsInline/>:<CameraOff/>}</div><button className="btn btn-secondary" onClick={startCamera}><Camera/> Camera सुरू करा</button><p className="status-message">{message}</p></section><section className="admin-card"><label><span className="form-label">Attendance Session</span><select className="form-input" value={selectedSession} onChange={e=>setSelectedSession(e.target.value)}><option value="">निवडा</option>{sessions.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><label><span className="form-label">विद्यार्थी</span><select className="form-input" value={selectedStudent} onChange={e=>setSelectedStudent(e.target.value)}><option value="">निवडा</option>{students.map(s=><option key={s.id} value={s.id}>{s.roll_number} — {s.name}</option>)}</select></label><div className="attendance-actions"><button className="btn btn-primary" onClick={()=>mark('face')}><UserCheck/> Face Verified Present</button><button className="btn btn-secondary" onClick={()=>mark('manual')}><CheckCircle2/> Manual Present</button></div></section></div></div>}
